### ISSUE TITLE
[Feature] Daily Lunch Options

### ISSUE THREAD

**Issue by weirdwater** [gempesaw/flowbot#5]
A command that lists day-specific lunch deals we know about.

Example output:

> User: .lunch
> flowbot: Lunch deals for today:
> - Double Stamp Tuesday at Fado's
> - $3 discount on pies at YourPie!

Data could be stored in a local database, a service like contentful or a plaintext file on the filesystem.

**Comment by gempesaw** [comment]
@arjo uhh i added the two other lunch deals I know about, but that only makes a total of 4 lunch deals, lol. if you know of any others, make a PR :D
